# Generated by Django 3.2.10 on 2021-12-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'зарезервировано'), ('not_reserved', 'не зарезервировано')], max_length=12)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
