# Generated by Django 3.2.10 on 2021-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='status',
            field=models.CharField(choices=[('reserved', 'зарезервировано'), ('not_reserved', 'не зарезервировано')], default='not_reserved', max_length=12),
        ),
    ]
